### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [beardog108/onionr#11]
Hello Sir. I'm a UI/UX and Graphics Designer. I want provide a logo for you. Would you mind if I propose a new logo design for your application as my Open Source Contribution?

Thanks before.

**Comment by beardog108** [comment]
anharismail, I can't promise I'll accept what you create, but if myself and Arinerron like it, I will accept it.

If you can, please try to provide an SVG file so we can use it in multiple sizes.

I'll credit you if it is accepted. Thank you for your interest.

**Comment by anharismail** [comment]
Hello, Sir @beardog108 . These are my logo proposal for your application.
I'm very welcome if you have any comments, opinions, or revisions. Please just tell me.
I'll provide all file types and sizes you needed.
Hope you like it.

### Version 1
![onionr ver 1](https://user-images.githubusercontent.com/37614260/40298775-6828b564-5d0e-11e8-8e74-e4caeb3f7d06.png)
### Version 2
![onionr ver 2](https://user-images.githubusercontent.com/37614260/40298803-7c52aed2-5d0e-11e8-8327-55793c4f07c7.png)

SVG File: https://drive.google.com/drive/u/1/folders/10CaJQUGbDyuQ5gmALpWLpArydCAyw4T4

**Comment by beardog108** [comment]
Hey @anharismail, thanks for your work. We like both of these, but we're going to go with version 1 for now. I can't think of any improvements on it right now.

Soon i'll put it in the readme and will use it elsewhere eventually. 
Thanks again!

**Comment by anharismail** [comment]
Thanks for using my logo Sir @beardog108 . Can I put this logo to a pull request, then you merge it?
